# Generated by Django 4.2.1 on 2023-06-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('finance', 'ca')], max_length=100)),
            ],
        ),
    ]
